language: perl

install:
  - cpanm git@github.com:plicease/PerlIO-gzip.git@Perl_520
  - cpanm -n Path::Class Git::Wrapper File::Temp HTTP::Tiny File::chdir autodie JSON::PP URI IPC::System::Simple PerlX::Maybe CPAN::ReleaseHistory

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

#before_script: /bin/true

script: HARNESS_IS_VERBOSE=1 prove -lv t xt

#after_script: /bin/true
