language: perl

install:
  - cpanm -n BackPAN::Index Path::Class Git::Wrapper File::Temp LWP::UserAgent File::chdir autodie JSON URI IPC::System::Simple PerlX::Maybe

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"

#before_script: /bin/true

script: HARNESS_IS_VERBOSE=1 prove -lv t xt

#after_script: /bin/true
