language: perl

install:
  - cpanm -n PerlIO::gzip
  - cpanm -n Path::Class Git::Wrapper File::Temp HTTP::Tiny File::chdir autodie JSON::PP URI IPC::System::Simple PerlX::Maybe CPAN::ReleaseHistory

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"

script: HARNESS_IS_VERBOSE=1 prove -lv t xt
