language: perl

sudo: false

install:
  - cpanm -n PerlIO::gzip Path::Class Git::Wrapper File::Temp HTTP::Tiny File::chdir autodie JSON::PP URI IPC::System::Simple PerlX::Maybe CPAN::ReleaseHistory
  - cpanm -n Archive::Extract

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

script:
  - HARNESS_IS_VERBOSE=1 prove -lv t 
